import Foundation
import KouenIPC

/// Formats cross-agent handoff briefs and encodes bracketed paste payloads for terminal injection.
public enum AgentHandoffBuilder: Sendable {
    /// Formats a structured, high-signal handoff brief from an existing session record to pass to a new agent.
    public static func buildBrief(from record: AgentSessionRecord, targetAgent: AgentKind? = nil, handoffNotePath: String? = nil) -> String {
        var lines: [String] = []

        let targetName = targetAgent?.displayName ?? "New Agent"
        lines.append("📋 Task Handoff from \(record.agentKind.displayName) to \(targetName)")
        lines.append("")

        // 1. Goal
        lines.append("## Goal")
        let goal = record.firstPrompt.trimmingCharacters(in: .whitespacesAndNewlines)
        if !goal.isEmpty {
            lines.append(goal)
        } else {
            lines.append(record.title)
        }
        lines.append("")

        // 2. Full context by reference, not by copy (same rule as the `handoff` skill: don't
        // duplicate what already lives in an artifact). Truncated turns cost tokens and cut
        // sentences mid-way; every agent can open the transcript itself when it needs more.
        lines.append("## Previous Session")
        if let handoffNotePath {
            lines.append("Handoff note written by \(record.agentKind.displayName) — read this first: `\(handoffNotePath)`")
        }
        if handoffNotePath != nil {
            lines.append("Full \(record.agentKind.displayName) transcript (read only if you need more context): `\(record.transcriptPath)`")
        } else {
            // Source couldn't write a note (often out of quota — the usual reason to hand off),
            // so the target does it with its own quota instead of skipping the context.
            lines.append("No handoff note could be generated by \(record.agentKind.displayName). Before anything else, read its full transcript: `\(record.transcriptPath)`")
            lines.append("Summarise it with your `handoff` skill (keep the summary in this conversation, don't save a file), then continue from that summary.")
        }
        lines.append("")

        // 3. Handoff note from repository if exists (SignalFileRouter)
        if let handoff = SignalFileRouter.handoffInfo(at: record.projectPath) {
            lines.append("## Handoff Note (from repo)")
            lines.append(handoff.note)
            if let skills = handoff.suggestedSkills {
                lines.append("**Suggested skills:** \(skills)")
            }
            lines.append("")
        }

        // 4. Instructions
        lines.append("## Next Steps")
        lines.append("Please inspect `git status` and `git diff` to understand current progress, then continue working on the task.")

        return lines.joined(separator: "\n").trimmingCharacters(in: .whitespacesAndNewlines)
    }

    // MARK: - Source-agent handoff note

    /// Prompt that runs the mattpocock `handoff` skill in `kind`'s own CLI (each agent has it
    /// installed; the doc is also requested as the final reply since a headless run can't answer
    /// a Write permission prompt). `nil` = no verified headless resume → transcript-only brief.
    public static func handoffSkillPrompt(for kind: AgentKind) -> String? {
        let tail = "Output the full document as your final reply as well."
        switch kind {
        case .claudeCode: return "/mattpocock-skills:handoff \(tail)"
        case .antigravity: return "/handoff \(tail)"   // ~/.agents/skills/handoff
        case .codex: return "$handoff \(tail)"          // Codex skill mention, ~/.codex/skills/handoff
        default: return nil
        }
    }

    /// Exit 0 isn't enough: a usage-limit notice or a hook's reply would otherwise become the
    /// note the brief tells the target to "read first". Require a real markdown document.
    public static func looksLikeHandoffDoc(_ text: String) -> Bool {
        text.count >= 300 && text.components(separatedBy: "\n").contains { $0.hasPrefix("#") }
    }

    /// Wraps text in terminal bracketed-paste markers (`\e[200~` … `\e[201~`) followed by `submit`,
    /// so the terminal program receives multi-line input as one atomic paste. ESC bytes are stripped
    /// from `text` first: an embedded `\e[201~` (e.g. terminal output quoted in a transcript) would
    /// otherwise end the paste early and turn the rest into live keystrokes.
    public static func bracketedPasteData(for text: String, submit: String = "\r") -> Data {
        let safe = text.replacingOccurrences(of: "\u{1b}", with: "")
        var data = Data("\u{1b}[200~".utf8)
        data.append(Data(safe.utf8))
        data.append(Data(("\u{1b}[201~" + submit).utf8))
        return data
    }
}
